# Generated by Django 5.2.8 on 2026-02-03 03:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectwallet',
            name='spen_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='dest_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectwallet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectwallet',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active (Funds Locked)'), ('COMPLETED', 'Completed (Funds Released)'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.bankaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income (Add to Bank)'), ('OUT', 'Expense (Deduct from Bank & Project)'), ('TRANSFER', 'Internal Transfer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(choices=[('BCA', 'Bank Central Asia'), ('Mandiri', 'Bank Mandiri'), ('BRI', 'Bank Rakyat Indonesia'), ('CASH', 'Cash on hand')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='projectwallet',
            name='client_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.projectwallet'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_out', to='api.bankaccount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_in', to='api.bankaccount'),
        ),
    ]
