# Generated by Django 5.2.8 on 2026-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='projectitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='period_amount',
            field=models.IntegerField(default=1, verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='period_unit',
            field=models.CharField(default='event', max_length=50),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='qty_amount',
            field=models.IntegerField(default=1, verbose_name='Qty'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='qty_unit',
            field=models.CharField(default='pax', max_length=50),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='volume_amount',
            field=models.IntegerField(default=1, verbose_name='Vol'),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='volume_unit',
            field=models.CharField(default='day', max_length=50),
        ),
    ]
