# Generated by Django 5.2.8 on 2026-02-08 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_projectitem_quantity_projectitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bank_account',
            new_name='account',
        ),
        migrations.AddField(
            model_name='projectitem',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='project_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='api.projectitem'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.projectwallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=20),
        ),
    ]
