# Generated by Django 5.2.8 on 2026-02-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_bank_account_transaction_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
